name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00caa6e4e9ebb3fd53261d219e35c76880a825ddd2320b889bf549b82011c170"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
