name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535ef4167945aedfdac3578533c26e9dc26d7e6241e3b664ce8b5aaceb8b923b"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
