name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698c6ee0cbba7909d7f617e6eb35430dd9f86b2d5da952511a95d4dd606a1d51"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
