name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85dd867f1f3edad9d5ddf622827be3956899c5dc29bf809890a388d6252040c8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
