name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9494edddd6ed9be846187b89a53e4ba566d586ba8b059bc58310459cabc7ad1b"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
