name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccf256fe012feecb7ac62e9ba349a365052da6e4a68b0aeb4b5905da0a44ccec"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
