name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eefae4abafc955119a45a72175916e5bb8c7a734102e7e08f427c9536a648b12"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
