name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f9bd4ae61b2de6e15b6564cee79ceca390ba36f58b655f222e0874c686be06"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
