name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e680fa652a9b4d9557739d1af41b1f002a63bf53f78c4af4e9db288d37e36762"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
