name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ffb21c0fc6dbc653d8586f82b2828a3ca899d1597e7ccb9b28204c141629d5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
