name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b34ca5b361f6609a894b3e7f4ed84858eacfdda3dc0ef29727d885738e85a90"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
