name = "testpack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bab0fcf39bfea25cb4ab4f241ef9ced7c96a2fe2e830e6b395882df57b3b5405"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
